name: graph_db
description: "Flutter graph database plugin"
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.4
  path_provider: ^2.1.5
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffigen: ^19.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      # ios:
      #   ffiPlugin: true
      # linux:
      #   ffiPlugin: true
      # macos:
      #   ffiPlugin: true
      # windows:
      #   ffiPlugin: true
